/*
    Install the following libraries. Use Version 8.0.0 (not latest):
• 	Microsoft.EntityFrameworkCare
• 	Microsoft.EntityFrameworkCore.SqlServer
• 	Microsoft.EntityFrameworkCore.Tools
    These allow migrations to run and SQL Server to be used.
*/
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Reflection.Emit;


namespace SchoolModel
{
    public class SchoolContext : DbContext
    {
        private readonly ILoggerFactory _loggerFactory;

        public SchoolContext(DbContextOptions<SchoolContext> options)
            : base(options) { }

        public DbSet<Student> Students => Set<Student>();
        public DbSet<Course> Courses => Set<Course>();
        public DbSet<Enrollment> Enrollments => Set<Enrollment>();

        public SchoolContext(DbContextOptions<SchoolContext> options, ILoggerFactory loggerFactory)
        : base(options)
        {
            _loggerFactory = loggerFactory;
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLoggerFactory(_loggerFactory);
            optionsBuilder.EnableSensitiveDataLogging();   // optional but helpful
        }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasDefaultSchema("School");

            modelBuilder.Entity<Enrollment>()
                .HasOne(e => e.Student)
                .WithMany(s => s.Enrollments)
                .HasForeignKey(e => e.StudentId);

            modelBuilder.Entity<Enrollment>()
                .HasOne(e => e.Course)
                .WithMany(c => c.Enrollments)
                .HasForeignKey(e => e.CourseId);

            /*
             * Note that EF Core makes "ID" columns as Identity columns
             * But when Inserting data, turns "Identity Insert" on so explicit PK values must be set.
             * EF Core needs a stable, known primary key value so it can:
                - insert the row during the migration
                - update the row if the seed changes
                - delete the row if the seed is removed
              * EF Core cannot rely on auto‑generated Identity values for this, because Identity values are:
                - generated by SQL Server
                - not known ahead of time
                - not guaranteed to be the same on every machine
            */
            modelBuilder.Entity<Student>().HasData(
                new Student { StudentId = 101, FirstName = "Ada", LastName = "Lovelace", Major = "Math" },
                new Student { StudentId = 102, FirstName = "Grace", LastName = "Hopper", Major = "ITP" }
            );

            modelBuilder.Entity<Course>().HasData(
                new Course { CourseId = 201, Tag = "ISP-136", Title = "Introduction to C#", Credits = 4 },
                new Course { CourseId = 202, Tag = "MTH-200", Title = "Discrete Math", Credits = 3 }
            );

            modelBuilder.Entity<Enrollment>().HasData(
                new Enrollment { EnrollmentId = 301, StudentId = 101, CourseId = 201 },
                new Enrollment { EnrollmentId = 302, StudentId = 102, CourseId = 202 }
            );

        }
    }


    [Table("Student")]
    public class Student
    {
        public int StudentId { get; set; }

        public required string FirstName { get; set; }
        public required string LastName { get; set; }

        public string? Major { get; set; }
        /// <summary>
        /// Gets or sets the collection of enrollments associated with the Student.
        /// A Student can have Many Enrollments--Can be enrolled in many courses
        /// </summary>
        public List<Enrollment> Enrollments { get; set; } = new();
        /// <summary>
        /// Uses LINQ to get the full name, consisting of the first name followed by the last name.
        /// </summary>
        public string FullName => $"{FirstName} {LastName}";
    }

    [Table("Course")]
    public class Course
    {
        public int CourseId { get; set; }

        public required string Tag { get; set; }
        public required string Title { get; set; }

        public int Credits { get; set; }
        /// <summary>
        /// Gets or sets the collection of enrollments associated with the Course.
        /// A Course can have Many Enrollments--Can have many Students enrolled in the course.
        /// </summary>
        public List<Enrollment> Enrollments { get; set; } = new();
    }
    /// <summary>
    /// Represents one student's enrollment in one course, including grade and related entities.
    /// </summary>
    /// <remarks>Includes navigation properties to the associated student and course.</remarks>
    [Table("Enrollment")]
    public class Enrollment
    {
        public int EnrollmentId { get; set; }
        public string? Grade { get; set; }

        // Foreign Keys
        public int StudentId { get; set; }
        public int CourseId { get; set; }

        // Navigation Properties
        public Student Student { get; set; } = null!;
        public Course Course { get; set; } = null!;
    }
}